PR for "Password validation rule"
dgraph-io/typhoon-ui pull request #5
Opened 2023-06-21 17:09 UTC by SiddeshUbale

This PR contains the following changes:-

1] Rule for password length validation (min 8 - max 21).
3] **dist folder** which we can refer to through Skyfall's package.json file for local testing (No need to merge into the main).

2023-06-21 19:02 UTC, kevinmingtarja requested changes
Left some minor comments for the `dist`, `.gitignore`, and `package.json`. Otherwise everything looks good!

2023-06-21 19:02 UTC, kevinmingtarja commented on dist/README.md
> +# 🌀 typhoon-ui
Can you remove all the `dist` from the changes, since we don't want to merge them.

2023-06-21 19:02 UTC, kevinmingtarja commented on package.json
> +    "framer-motion": "^4.0.0",
I think this shouldn't be here, since it's already there under `peerDependencies`.

2023-06-21 19:13 UTC, sanjayk-github-dev commented on src/hooks/form/rules.ts
> +        message: "Password length should be between 8 to 21 characters",
Let's use min of 8 and max of 64 characters. This matches AWS password policy.

2023-06-23 17:33 UTC, kevinmingtarja approved these changes
LGTM!

2023-06-23 17:34 UTC, merged